"""
export_images.py — dump CIFAR-10 test images as a C header for the CVA5 driver.

Images are stored as raw uint8 RGB in raster order (channels-last), which is
both the most compact form and the order the accelerator expects. The driver
converts uint8 -> ap_fixed<14,5> at runtime with integer arithmetic.

Size: 3072 bytes per image. Check this against your CVA5 memory before
raising N_IMAGES -- the array lands in .rodata and there is no DRAM in this
design.

Usage:
    python export_images.py --n 8 --classes 6 8 --out images.h
"""

import argparse
import numpy as np
import torch
import torchvision
import torchvision.transforms as transforms

NAMES = ["airplane", "automobile", "bird", "cat", "deer",
         "dog", "frog", "horse", "ship", "truck"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=8, help="images to export")
    ap.add_argument("--classes", nargs=2, type=int, default=[6, 8],
                    help="two CIFAR class indices (default frog ship)")
    ap.add_argument("--out", default="images.h")
    ap.add_argument("--model", default=None,
                    help="trained model, for the host accuracy check "
                         "(default: model_<A>_<B>.pt)")
    args = ap.parse_args()

    a, b = args.classes
    model_path = args.model or f"model_{a}_{b}.pt"
    ds = torchvision.datasets.CIFAR10(root="./data", train=False,
                                      download=True, transform=None)
    targets = np.array(ds.targets)
    idx = np.where((targets == a) | (targets == b))[0]

    # Take an even mix of both classes rather than the first N, which would
    # be dominated by whichever class appears earlier.
    idx_a = [i for i in idx if targets[i] == a][: args.n // 2]
    idx_b = [i for i in idx if targets[i] == b][: args.n - args.n // 2]
    picks = idx_a + idx_b

    imgs = np.stack([np.array(ds.data[i], dtype=np.uint8) for i in picks])
    labels = [0 if targets[i] == a else 1 for i in picks]

    # Host accuracy on exactly these images, printed for comparison with the
    # board. Not emitted into the header: bench.c checks hardware against
    # software on the same core, which is a stronger test than against a
    # constant baked in here.
    ref = None
    try:
        import torch.nn as nn

        class SmallCNN(nn.Module):
            def __init__(self, n_classes=2):
                super().__init__()
                self.c1 = nn.Conv2d(3, 4, 3, padding=1)
                self.r1 = nn.ReLU()
                self.p1 = nn.MaxPool2d(4)
                self.c2 = nn.Conv2d(4, 8, 3, padding=1)
                self.r2 = nn.ReLU()
                self.p2 = nn.MaxPool2d(4)
                self.fl = nn.Flatten()
                self.fc = nn.Linear(8 * 2 * 2, n_classes)

            def forward(self, x):
                x = self.p1(self.r1(self.c1(x)))
                x = self.p2(self.r2(self.c2(x)))
                return self.fc(self.fl(x))

        m = SmallCNN()
        m.load_state_dict(torch.load(model_path, map_location="cpu"))
        m.eval()
        X = torch.from_numpy(
            np.transpose(imgs, (0, 3, 1, 2)).astype(np.float32) / 255.0)
        with torch.no_grad():
            ref = m(X).numpy()
        print(f"Host reference: {(ref.argmax(1) == np.array(labels)).mean()*100:.1f}% "
              f"on these {len(picks)} images")
    except Exception as e:
        print(f"(no reference logits: {e})")

    with open(args.out, "w") as f:
        f.write(f"""/* Generated by export_images.py -- do not edit.
 *
 * {len(picks)} CIFAR-10 test images, {NAMES[a]} (label 0) vs {NAMES[b]} (label 1).
 * Raw uint8 RGB, raster order, channels-last: img[(y*32+x)*3+c].
 * That ordering is what the accelerator expects -- see examples/sw/bench.c.
 */

#ifndef IMAGES_H
#define IMAGES_H
#include <stdint.h>

#define N_IMAGES {len(picks)}
#define IMG_BYTES {32*32*3}

static const char *const CLASS_NAMES[2] = {{"{NAMES[a]}", "{NAMES[b]}"}};

static const uint8_t IMAGE_LABELS[N_IMAGES] = {{
    {", ".join(str(l) for l in labels)}
}};
""")

        f.write("\nstatic const uint8_t IMAGES[N_IMAGES][IMG_BYTES] = {\n")
        for k, im in enumerate(imgs):
            flat = im.reshape(-1)          # already HWC from CIFAR data
            f.write(f"  /* {k}: {NAMES[a if labels[k]==0 else b]} */ {{\n")
            for i in range(0, len(flat), 24):
                f.write("    " + ",".join(f"{v:3d}" for v in flat[i:i+24]) + ",\n")
            f.write("  },\n")
        f.write("};\n\n#endif /* IMAGES_H */\n")

    size_kb = len(picks) * 3072 / 1024
    print(f"Wrote {args.out}: {len(picks)} images, {size_kb:.0f} KB of .rodata")
    print("Check that against your CVA5 memory size before increasing --n.")


if __name__ == "__main__":
    main()
