"""
export_weights.py — dump trained weights as Q9 fixed-point C arrays.

Q9 means 9 fractional bits, i.e. 1.0 == 512 -- the same scale as the
accelerator's ap_fixed<14,5>, so the software and hardware results are
directly comparable rather than needing separate calibration.

Products of two Q9 values are Q18 and accumulate in int32: the widest layer
sums 36 terms of at most 512*512, about 9.4M, well inside int32.

Usage:
    python export_weights.py model_6_8.pt --out weights.h
"""

import argparse
import numpy as np
import torch
import torch.nn as nn

Q = 9
ONE = 1 << Q          # 512


class SmallCNN(nn.Module):
    def __init__(self, n_classes=2):
        super().__init__()
        self.c1 = nn.Conv2d(3, 4, 3, padding=1)
        self.r1 = nn.ReLU()
        self.p1 = nn.MaxPool2d(4)
        self.c2 = nn.Conv2d(4, 8, 3, padding=1)
        self.r2 = nn.ReLU()
        self.p2 = nn.MaxPool2d(4)
        self.fl = nn.Flatten()
        self.fc = nn.Linear(8 * 2 * 2, n_classes)

    def forward(self, x):
        x = self.p1(self.r1(self.c1(x)))
        x = self.p2(self.r2(self.c2(x)))
        return self.fc(self.fl(x))


def quant(a, scale=ONE):
    q = np.round(np.asarray(a, dtype=np.float64) * scale).astype(np.int64)
    lo, hi = q.min(), q.max()
    if lo < -32768 or hi > 32767:
        raise SystemExit(f"[!] quantized value out of int16 range: [{lo},{hi}]")
    return q.astype(np.int16), lo, hi


def emit(f, name, arr, comment):
    flat = arr.reshape(-1)
    f.write(f"\n/* {comment} */\n")
    f.write(f"static const int16_t {name}[{flat.size}] = {{\n")
    for i in range(0, flat.size, 12):
        f.write("    " + ", ".join(f"{v:6d}" for v in flat[i:i+12]) + ",\n")
    f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("model")
    ap.add_argument("--out", default="weights.h")
    args = ap.parse_args()

    m = SmallCNN()
    m.load_state_dict(torch.load(args.model, map_location="cpu"))
    m.eval()

    peak = max(p.abs().max().item() for p in m.parameters())
    print(f"peak |param| = {peak:.4f}")
    if peak < 0.193:
        raise SystemExit("[!] weights look untrained -- refusing to export")

    sd = {k: v.detach().numpy() for k, v in m.state_dict().items()}

    # Biases are stored in Q18 so they add straight onto the Q18 accumulator
    # without a shift in the inner loop.
    parts = []
    for name, key, scale, comment in [
        ("W1", "c1.weight", ONE,       "conv1 weights [4][3][3][3], Q9"),
        ("B1", "c1.bias",   ONE * ONE, "conv1 bias [4], Q18"),
        ("W2", "c2.weight", ONE,       "conv2 weights [8][4][3][3], Q9"),
        ("B2", "c2.bias",   ONE * ONE, "conv2 bias [8], Q18"),
        ("W3", "fc.weight", ONE,       "fc weights [2][32], Q9"),
        ("B3", "fc.bias",   ONE * ONE, "fc bias [2], Q18"),
    ]:
        a = sd[key]
        if scale == ONE * ONE:
            # Q18 biases can exceed int16; store as int32 instead.
            q = np.round(a.astype(np.float64) * scale).astype(np.int32)
            parts.append((name, q, comment, True))
            print(f"  {name:3} {str(a.shape):18} Q18 int32 range "
                  f"[{q.min()}, {q.max()}]")
        else:
            q, lo, hi = quant(a, scale)
            parts.append((name, q, comment, False))
            print(f"  {name:3} {str(a.shape):18} Q9  int16 range [{lo}, {hi}]")

    with open(args.out, "w") as f:
        f.write(f"""/* Generated by export_weights.py -- do not edit.
 *
 * Trained weights in Q{Q} fixed point (1.0 == {ONE}), matching the
 * accelerator's ap_fixed<14,{14-Q}> scale so software and hardware results are
 * directly comparable.
 *
 * Weights are Q9 int16. Biases are pre-scaled to Q18 int32 so they add
 * directly onto the product accumulator with no shift in the inner loop.
 */

#ifndef WEIGHTS_H
#define WEIGHTS_H
#include <stdint.h>

#define Q_SHIFT {Q}
#define Q_ONE   {ONE}
""")
        for name, q, comment, is32 in parts:
            flat = q.reshape(-1)
            ctype = "int32_t" if is32 else "int16_t"
            f.write(f"\n/* {comment} */\n")
            f.write(f"static const {ctype} {name}[{flat.size}] = {{\n")
            for i in range(0, flat.size, 12):
                f.write("    " + ", ".join(f"{v:8d}" for v in flat[i:i+12]) + ",\n")
            f.write("};\n")
        f.write("\n#endif /* WEIGHTS_H */\n")

    total = sum(p.reshape(-1).size * (4 if is32 else 2)
                for _, p, _, is32 in parts)
    print(f"\nWrote {args.out}: {total} bytes of .rodata")


if __name__ == "__main__":
    main()
