#!/usr/bin/env python3
"""Turn an ELF into a Tcl image that OpenOCD can write over System Bus Access.

    elf-to-load-tcl.py <cross-prefix> <base-addr> <elf> <out.tcl>

Emits:
    set LOAD_ADDR  <base>
    set LOAD_WORDS { 0x... 0x... ... }

The loader procs in examples/xilinx/openocd/cva5-pynq-z2-p1.cfg consume these.
Writing a Tcl list keeps the whole flow inside OpenOCD's own interpreter, which
has no portable way to read a binary file itself.
"""
import subprocess
import sys


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    cross, base, elf, out = sys.argv[1], int(sys.argv[2], 0), sys.argv[3], sys.argv[4]

    raw = elf + ".bin"
    subprocess.run([cross + "objcopy", "-O", "binary", elf, raw], check=True)
    with open(raw, "rb") as f:
        data = f.read()

    if len(data) % 4:
        data += b"\0" * (4 - len(data) % 4)
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]

    with open(out, "w") as f:
        f.write("# Generated by tools/elf-to-load-tcl.py -- do not edit\n")
        f.write("set LOAD_ADDR 0x%08x\n" % base)
        f.write("set LOAD_WORDS {\n")
        for i in range(0, len(words), 8):
            f.write("  " + " ".join("0x%08x" % w for w in words[i:i + 8]) + "\n")
        f.write("}\n")
        # OpenOCD echoes the value of the last command in a sourced file;
        # end on something empty so the word list is not dumped to the console.
        f.write('set LOAD_QUIET ""\n')

    print("%s: %d words (%d bytes) at 0x%08x" % (out, len(words), len(data), base))


if __name__ == "__main__":
    main()
