#!/usr/bin/env python3
"""Produce include-free copies of pulp-platform SystemVerilog sources.

Vivado's IP packager (`ipx::package_project -import_files`) flattens every
source into one directory, so a `` `include "axi/typedef.svh" `` inside a
vendored file can no longer resolve. In the pulp sources those includes only
ever appear *after* the struct-port module, to support the `*_intf` variants
built on SystemVerilog interfaces -- which a Vivado block design cannot use
anyway. Truncating each file at its first `include` therefore keeps exactly
the part this project instantiates and drops the part that cannot be packaged.

Usage:
    tools/vendor-pulp-sv.py                 # regenerate examples/fpga/vendor
    tools/vendor-pulp-sv.py --check         # fail if the copies are stale

The generated files are committed so that building the IP needs nothing but
Vivado; rerun this after bumping a submodule.
"""

import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "examples" / "fpga" / "vendor"

# Files that need truncating, relative to the repository root.
SOURCES = [
    "third_party/axi/src/axi_cut.sv",
]


def submodule_version(path: pathlib.Path) -> str:
    """A human-readable version for the submodule that owns `path`."""
    for parent in path.parents:
        if (parent / ".git").exists():
            try:
                tag = subprocess.run(
                    ["git", "-C", str(parent), "describe", "--tags", "--always"],
                    capture_output=True, text=True, check=True).stdout.strip()
            except subprocess.CalledProcessError:
                return "unknown"
            return tag
    return "unknown"


def render(src: pathlib.Path, rel: str) -> str:
    lines = src.read_text().splitlines(keepends=True)
    cut = len(lines)
    for i, line in enumerate(lines):
        if line.lstrip().startswith("`include"):
            cut = i
            break
    body = "".join(lines[:cut]).rstrip() + "\n"
    header = (
        f"// GENERATED by tools/vendor-pulp-sv.py -- do not edit.\n"
        f"//\n"
        f"// Source : {rel} ({submodule_version(src)})\n"
        f"// Change : truncated at the first `include, which drops the\n"
        f"//          SystemVerilog-interface (`*_intf`) variants. Vivado's IP\n"
        f"//          packager flattens sources, so the include paths in those\n"
        f"//          variants cannot resolve, and a block design cannot use\n"
        f"//          interface ports in any case.\n"
        f"//\n"
        f"// Regenerate with: tools/vendor-pulp-sv.py\n"
        f"\n"
    )
    return header + body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if a generated file is out of date")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for rel in SOURCES:
        src = ROOT / rel
        if not src.exists():
            print(f"missing {rel} -- did you run 'git submodule update --init'?",
                  file=sys.stderr)
            return 1
        dst = OUT / src.name
        text = render(src, rel)
        if args.check:
            if not dst.exists() or dst.read_text() != text:
                stale.append(str(dst.relative_to(ROOT)))
        else:
            dst.write_text(text)
            print(f"wrote {dst.relative_to(ROOT)}")

    if stale:
        print("stale vendored files: " + ", ".join(stale), file=sys.stderr)
        print("run tools/vendor-pulp-sv.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
